baseURL = ''
languageCode = 'en-us'
title = 'The Fumbling Physicist'
theme = ["github.com/theNewDynamic/gohugo-theme-ananke"]
show_reading_time = true
[[params.ananke_socials]]
name = "linkedin"
url = "https://www.linkedin.com/in/galwiner/"
label = "My Linkedin"

[[params.ananke_socials]]
name = "twitter"
url = "https://twitter.com/galwiner"
label = "My Twitter"

[[params.ananke_socials]]
name = "youtube"
url = "https://www.youtube.com/channel/UCE3KRsjYDMRLZglSU8_zraA"
label = "My Twitter"
